/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java-conventions")
    id("io.micronaut.application")
}
dependencies {
    // micronaut-runtime
    implementation("io.micronaut:micronaut-runtime")
}

micronaut {
    version.set("3.8.0")

}