r2dbc:
  datasources:
    default:
      url: ${DB_URL:`r2dbc:h2:file://Users/nanfeng/IdeaProjects/vanaheimr/vanaheimr;AUTO_SERVER=TRUE`}
      username: ${DB_USER:`sa`}
      password: ${DB_PASSWORD:``}
